prefix :       <http://example.org/> 
prefix schema: <http://schema.org/> 
prefix xsd:    <http://www.w3.org/2001/XMLSchema#> 
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?x ?friend WHERE {
 ?x schema:knows ?friend .
}