prefix : <http://example.org/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix schema: <http://schema.org/> 

SELECT ?p WHERE {
 ?p a :Person 
 { SELECT ?p { 
    ?p schema:name ?name
  } GROUP BY ?p HAVING (COUNT(*)=1)
 }
 { SELECT ?p {
    ?p schema:name ?name 
    FILTER ( isLiteral(?name) && 
             datatype(?name) = xsd:string )
   } GROUP BY ?p HAVING (COUNT(*)=1)
 } 
 { { SELECT ?p (count(*) as ?counter1) { 
    ?p schema:knows ?known
  } GROUP BY ?p 
 }
  { SELECT ?p (count(*) as ?counter2) { 
    ?p schema:knows ?k
    FILTER ( isIRI(?k))
  } GROUP BY ?p HAVING (COUNT(*)>=1)
 } } FILTER (?counter1 = ?counter2)
}

